version: "3.9"
services:
  # --- BACKENDS ---
  backend-admin:
    build: ./apps/backend-admin
    environment:
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
    expose:
      - "3003"

  backend-api:
    build: ./apps/backend-api
    environment:
      - MONGO_URI=${MONGO_URI}
    expose:
      - "3002"

  bot:
    build: ./apps/bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
    expose:
      - "3001"

  # --- FRONTENDS ---
  frontend-admin:
    build: ./apps/frontend-admin
    expose:
      - "80"

  frontend-landing:
    build: ./apps/frontend-landing
    expose:
      - "80"

  # --- NGINX ---
  nginx:
    image: nginx:stable
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend-admin
      - frontend-landing
      - backend-admin
      - backend-api
